### ISSUE TITLE
remove gaps between items

### ISSUE THREAD

**Issue by DreadKnight** [FreezingMoon/AncientBeast-Website#103]
On the contribution page, the icons on the right card (or the sections) shouldn't have any spacing between them, that way everything fits nicely within the card's frame instead of overlapping it at the bottom https://ancientbeast.com/contribute

![Screenshot_20220813_045527](https://user-images.githubusercontent.com/587487/184464258-f8b0c0ef-fe82-4a18-bc46-b98b2cedcf01.jpg)

**Comment by Dhananjay-12** [comment]
Hi , I guess I understood the problem. The icons are behaving like this due the ```display: table-cell;``` in the wrapper class.
If this resolves this can I fix this? Thanks

**Comment by DreadKnight** [comment]
> Hi , I guess I understood the problem. The icons are behaving like this due the `display: table-cell;` in the wrapper class. If this resolves this can I fix this? Thanks

Heya! Sure thing, feel free to poke at it. I've assigned you to it, soft deadline 2 weeks.

**Comment by Dhananjay-12** [comment]
hi, do you received the changes?

**Comment by DreadKnight** [comment]
> hi, do you received the changes?

Heya! You need to make a pull request (PR) from your branch that gets reviewed https://github.com/FreezingMoon/AncientBeast-Website/pulls

I see you made changes by commenting a line, usually just go ahead and remove that code line if you tested stuff.

**Comment by Dhananjay-12** [comment]
Thanks I made the changes. Made a PR too  : ]

**Comment by DreadKnight** [comment]
> Thanks I made the changes. Made a PR too : ]

Alrighty, left you feedback on the PR.
