### ISSUE TITLE
Add Custom Scrollbar and Custom Text Selection Color According to theme of the website

### ISSUE THREAD

**Issue by pjoshi999** [FreezingMoon/AncientBeast-Website#109]
**Feature Description.**
Add Custom Scrollbar and Custom Text Selection Color According to theme of the website

**Why is this feature needed ?**
Custom scrollbars and selection color are essential to improve a website's aesthetics and user experience. By aligning these design elements with the website's theme, it ensures visual consistency and branding, creating a polished and cohesive look. Default browser scrollbars and selection colors often clash with the website's style, making customization crucial for a visually appealing design. In summary, custom scrollbars and selection colors are necessary for improving aesthetics, brand consistency, user experience, accessibility, and overall website success.

Please Assign this task to me.

**Comment by DreadKnight** [comment]
@pjoshi999 I've transferred this issue to the proper repository that deals with the game's website itself. Also assigned.
