### ISSUE TITLE
pointer in floating table header

### ISSUE THREAD

**Issue by DreadKnight** [FreezingMoon/AncientBeast-Website#16]
When the table from units/?view=table is scrolled down having the header floating, hovering the mouse over icons from it that can rearrange the columns on click should show the cursor as a pointer.

**Comment by DreadKnight** [comment]
@ktiedt Seems with the new patch, table can't be sorted at all xD
This is pretty important as I use this page as a tool to balance units.

**Comment by ktiedt** [comment]
Worked fine for me...

**Comment by DreadKnight** [comment]
@ktiedt check this one over here: http://ancientbeast.com/units/?view=table
When you click on an icon (without scrolling down), the table sorts itself out.

**Comment by ktiedt** [comment]
Yeah... still works fine for me...
