### ISSUE TITLE
unit viewer should update abilities

### ISSUE THREAD

**Issue by DreadKnight** [FreezingMoon/AncientBeast-Website#33]
The unit viewer needs to update the abilities when changing to a new unit.
http://ancientbeast.com/units/?view=viewer#focus

This functionality is also implemented in the game itself, so code could be forked from there or it could even be turned into a module and reused between the two.

**Comment by DreadKnight** [comment]
The code I mentioned is probably over here https://github.com/FreezingMoon/AncientBeast-Website/blob/master/game/src/interface.js#L518 (game folder is not to be altered in this folder usually, will have to get around to https://github.com/FreezingMoon/AncientBeast/issues/837 )

**Comment by ktiedt** [comment]
I think this might be covered by the work Sharkoon is doing

**Comment by DreadKnight** [comment]
Yes, partially. If he actually does the work. There will be a bit more work required to migrate the website to modern web dev pipeline / architecture / infrastructure, which I'm not to keen about. Would prefer a nice quick fix for this by then xD

**Comment by ktiedt** [comment]
If his work addresses this, it will be an easy thing to bring into the website side too, part of the magic of web components ;)

**Comment by DreadKnight** [comment]
@ktiedt you're talking ideal fix that might be months away, I'm talking a quick fix as visitors run into something broken for months now and get a papercut.
