### ISSUE TITLE
less crowded website footer

### ISSUE THREAD

**Issue by DreadKnight** [FreezingMoon/AncientBeast-Website#6]
The website footer could be less crowded. Will need to cut down on elements, perhaps remove the donation related ones.

**Comment by AwakeningLukas** [comment]
My full suggestion was to add 2 pages, one for contact us with all the various (and sometimes less used) networks on and email, form, etc on it and one page with the "support us" stuff, donations, bounties, ways to contribute, github, etc.  Leave just the main stuff Facebook, Twitter, GameJolt, and G+ at the bottom.

**Comment by DreadKnight** [comment]
Regarding the "contact us" page, that's the overall idea for the chat page (I'm trying to keep header navigation item names rather short) http://ancientbeast.com/chat - so I'll try to streamline the page better.

The other stuff is in http://ancientbeast.com/contribute/ - which is accessible from the index page.

Only 4 items will make the footer seem a bit odd, might have to include names to make the things easier to click as well; ranking pages tend to consider the clicking space for a link in their algorithms anyway, so will have less complaints from them that way. And if GameJolt is in there, might as well have Indiedb there and the email button has proven useful at times, hmm...

**Comment by AwakeningLukas** [comment]
contribute should be in the main header .... seems like blog, chat, social media, and contribute could all be under one or two buttons, maybe contribute in place of chat, and contact us in place of blog, then there are no extra buttons.

**Comment by AwakeningLukas** [comment]
The wording "chat" gives the impression that there is like an IRC chatroom or something to interact with other players, which is why I think it should be more contact/contact us instead.

**Comment by DreadKnight** [comment]
Well, up until a few months ago there used to be an IRC applet inside the chat page. Now there's a gitter one along with discord widget, so it still kinda is about chatting.

"Contribute" is kinda long compared to the other ones there so it messes with my OCD, sigh xD

**Comment by DreadKnight** [comment]
Sometimes I just feel like killing the whole website header and just leaving the "Ancient Beast" graphic, having big buttons for everything on the homepage and get it done with. Kinda like phones display app icons.
