### ISSUE TITLE
no div side padding

### ISSUE THREAD

**Issue by DreadKnight** [FreezingMoon/AncientBeast-Website#97]
There should be no padding on left/ride for website divs, to better display on mobiles, even if the "desktop mode" is enabled.

**Comment by KarlaChen** [comment]
@DreadKnight Can I try it?

**Comment by DreadKnight** [comment]
@KarlaChen Feel free to do so!

**Comment by KarlaChen** [comment]
can I get more detail the padding you want to remove?

**Comment by DreadKnight** [comment]
@KarlaChen You would have to check the website on a phone. The idea is to have the divs stretch pretty much from side to side (like they used to a while ago), having things properly visible.

**Comment by Dhananjay-12** [comment]
Hi ,is this issue still on progress?

**Comment by DreadKnight** [comment]
> Hi ,is this issue still on progress?

Heya! I checked out the website on desktop, half the screen and simulated mobile and also on phone and seems to me that this is no longer an issue, so I'll close it. Feel free to take a peek at our game's issue tracker as well https://github.com/FreezingMoon/AncientBeast/issues
